name: zodiac_gems
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.2
  logger: 2.3.0
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  equatable: 2.0.5
  firebase_auth: 4.17.7
  firebase_auth_platform_interface: 7.1.7
  firebase_auth_web: 5.9.7
  firebase_core: 2.26.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.11.5
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  http: 1.2.0
  intl: 0.18.1
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.8
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  simple_gradient_text: 1.2.3
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  flutter_gradient_colors: ^2.1.1

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
